stages:
  - build
  - tag
  - sign

variables:
  HYDROQC2MQTT_VERSION: 0.9.1


.build_generic: &build_generic
  tags:
    - docker
    - multi-arch
  stage: build
  image: docker:22.06-rc
  services:
    - docker:22.06-rc-dind
  except:
    - tags
  script:
    - docker version
    - docker buildx build 
      --platform linux/${ARCH} 
      -t ${CI_REGISTRY_IMAGE}/${ARCH}:${CI_COMMIT_SHORT_SHA} 
      -f ./hydroqc/Dockerfile 
      --build-arg BUILD_FROM=ghcr.io/home-assistant/${ARCH}-base-python:3.10-alpine3.16  
      --build-arg BUILD_ARCH=${ARCH} 
      --build-arg BUILD_HYDROQC2MQTT_VERSION=${HYDROQC2MQTT_VERSION} 
      hydroqc
    - docker tag ${CI_REGISTRY_IMAGE}/${ARCH}:${CI_COMMIT_SHORT_SHA} ${CI_REGISTRY_IMAGE}/${ARCH}:${CI_COMMIT_REF_NAME}
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push ${CI_REGISTRY_IMAGE}/${ARCH}:${CI_COMMIT_SHORT_SHA} 
    - docker push ${CI_REGISTRY_IMAGE}/${ARCH}:${CI_COMMIT_REF_NAME}


.tag_generic: &tag_generic
  tags:
    - docker
  stage: tag
  image: docker:22.06-rc
  services:
    - docker:22.06-rc-dind
  only:
    - tags
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull ${CI_REGISTRY_IMAGE}/${ARCH}:${CI_COMMIT_SHORT_SHA}
    - docker tag ${CI_REGISTRY_IMAGE}/${ARCH}:${CI_COMMIT_SHORT_SHA} ${CI_REGISTRY_IMAGE}/${ARCH}:${CI_COMMIT_REF_NAME}
    - docker push ${CI_REGISTRY_IMAGE}/${ARCH}:${CI_COMMIT_REF_NAME}


.sign_generic: &sign_generic
  tags:
    - hydroqc
    - sign
  stage: sign
  image: registry.gitlab.com/hydroqc/hydroqc-base-container/addon-sign:20230116100442
  rules:
    - if: '$CI_COMMIT_TAG != null && $CI_COMMIT_REF_PROTECTED == "true"'  # Only on protected tags
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull ${CI_REGISTRY_IMAGE}/${ARCH}:${CI_COMMIT_REF_NAME}
    - cas login
    - cas notarize docker://${CI_REGISTRY_IMAGE}/${ARCH}:${CI_COMMIT_REF_NAME}
    - docker rmi ${CI_REGISTRY_IMAGE}/${ARCH}:${CI_COMMIT_REF_NAME}



build_amd64:
  variables:
    ARCH: amd64
  <<: *build_generic

build_i386:
  variables:
    ARCH: i386
  <<: *build_generic

build_armhf:
  variables:
    ARCH: armhf
  <<: *build_generic

build_armv7:
  variables:
    ARCH: armv7
  <<: *build_generic

build_aarch64:
  variables:
    ARCH: aarch64
  <<: *build_generic



tag_amd64:
  variables:
    ARCH: amd64
  <<: *tag_generic

tag_i386:
  variables:
    ARCH: i386
  <<: *tag_generic

tag_armhf:
  variables:
    ARCH: armhf
  <<: *tag_generic

tag_armv7:
  variables:
    ARCH: armv7
  <<: *tag_generic

tag_aarch64:
  variables:
    ARCH: aarch64
  <<: *tag_generic



sign_amd64:
  needs: ["tag_amd64"]
  variables:
    ARCH: amd64
  <<: *sign_generic

sign_i386:
  needs: ["tag_i386"]
  variables:
    ARCH: i386
  <<: *sign_generic

sign_armhf:
  needs: ["tag_armhf"]
  variables:
    ARCH: armhf
  <<: *sign_generic

sign_armv7:
  needs: ["tag_armv7"]
  variables:
    ARCH: armv7
  <<: *sign_generic

sign_aarch64:
  needs: ["tag_aarch64"]
  variables:
    ARCH: aarch64
  <<: *sign_generic
