stages:
- build

services:
  - docker:22.06-rc-dind

variables:
  HYDROQC2MQTT_VERSION: main

.build_generic: &build_generic
  stage: build
  image: docker:22.06-rc
  script:
    - docker version
    - docker buildx build 
      --platform linux/${ARCH} 
      -t ${CI_REGISTRY_IMAGE}/${ARCH}:${CI_COMMIT_SHORT_SHA} 
      -f ./hydroqc/Dockerfile 
      --build-arg BUILD_FROM=ghcr.io/home-assistant/${ARCH}-base-python:3.10-alpine3.16  
      --build-arg BUILD_ARCH=${ARCH} 
      --build-arg BUILD_HYDROQC2MQTT_VERSION=${HYDROQC2MQTT_VERSION} 
      --build-arg TEMPIO_VERSION=2021.05.0 
      hydroqc
    - docker tag ${CI_REGISTRY_IMAGE}/${ARCH}:${CI_COMMIT_SHORT_SHA} ${CI_REGISTRY_IMAGE}/${ARCH}:${CI_COMMIT_REF_NAME}
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push ${CI_REGISTRY_IMAGE}/${ARCH}:${CI_COMMIT_SHORT_SHA} 
    - docker push ${CI_REGISTRY_IMAGE}/${ARCH}:${CI_COMMIT_REF_NAME}

# Build
build_amd64:
  variables:
    ARCH: amd64
  <<: *build_generic

build_i386:
  variables:
    ARCH: i386
  <<: *build_generic

build_armhf:
  variables:
    ARCH: armhf
  <<: *build_generic

build_armv7:
  variables:
    ARCH: armv7
  <<: *build_generic

build_aarch64:
  variables:
    ARCH: aarch64
  <<: *build_generic
